### ISSUE TITLE
Pre-trained autoencoder loading error

### ISSUE THREAD

**Issue by biubiubiiu** [Yizhou-Li-CV/ECNet#1]
Training ECNet would raise an error when tries loading the pre-trained autoencoder:

```
Unexpected key(s) in state_dict: "Up4.up.1.weight", "Up4.up.1.bias", "Up4.up.2.weight", "Up4.up.2.bias"..... 
```

It seems that the module is saved in `DataParallel` when trains with GPU, which stores the model in `module`, and is trying to load it without DataParallel. 

```python
# code snippet from build_networks.py
def init_net(net, init_type='normal', init_gain=0.02, gpu_ids=[], init=True):
    if len(gpu_ids) > 0:
        ...
        net = torch.nn.DataParallel(net, gpu_ids)  # wrapped by DataParallel

# code snippet from base_model.py
def load_networks(self):
   ...
   if isinstance(net, torch.nn.DataParallel):
      net = net.module  # unwrapped as nn.Module

   state_dict = torch.load(load_path, map_location=str(self.device))  # the pre-trained network, save with DataParallel
   net.load_state_dict(model_dict)  # error happens here
```

**Comment by Yizhou-Li-CV** [comment]
Thank you very much for your comments. I'm afraid I failed to reproduct this error. May I Ask were you trying to train the network with CPU?

**Comment by Yizhou-Li-CV** [comment]
> Training ECNet would raise an error when tries loading the pre-trained autoencoder:
> 
> ```
> Unexpected key(s) in state_dict: "Up4.up.1.weight", "Up4.up.1.bias", "Up4.up.2.weight", "Up4.up.2.bias"..... 
> ```
> 
> It seems that the module is saved in `DataParallel` when trains with GPU, which stores the model in `module`, and is trying to load it without DataParallel.
> 
> ```python
> # code snippet from build_networks.py
> def init_net(net, init_type='normal', init_gain=0.02, gpu_ids=[], init=True):
>     if len(gpu_ids) > 0:
>         ...
>         net = torch.nn.DataParallel(net, gpu_ids)  # wrapped by DataParallel
> 
> # code snippet from base_model.py
> def load_networks(self):
>    ...
>    if isinstance(net, torch.nn.DataParallel):
>       net = net.module  # unwrapped as nn.Module
> 
>    state_dict = torch.load(load_path, map_location=str(self.device))  # the pre-trained network, save with DataParallel
>    net.load_state_dict(model_dict)  # error happens here
> ```

**Comment by Yizhou-Li-CV** [comment]
> Training ECNet would raise an error when tries loading the pre-trained autoencoder:
> 
> ```
> Unexpected key(s) in state_dict: "Up4.up.1.weight", "Up4.up.1.bias", "Up4.up.2.weight", "Up4.up.2.bias"..... 
> ```
> 
> It seems that the module is saved in `DataParallel` when trains with GPU, which stores the model in `module`, and is trying to load it without DataParallel.
> 
> ```python
> # code snippet from build_networks.py
> def init_net(net, init_type='normal', init_gain=0.02, gpu_ids=[], init=True):
>     if len(gpu_ids) > 0:
>         ...
>         net = torch.nn.DataParallel(net, gpu_ids)  # wrapped by DataParallel
> 
> # code snippet from base_model.py
> def load_networks(self):
>    ...
>    if isinstance(net, torch.nn.DataParallel):
>       net = net.module  # unwrapped as nn.Module
> 
>    state_dict = torch.load(load_path, map_location=str(self.device))  # the pre-trained network, save with DataParallel
>    net.load_state_dict(model_dict)  # error happens here
> ```

Thank you very much for your comments. I'm afraid I failed to reproduce this error. May I ask were you trying to train the network with CPU?

**Comment by awhitewhale** [comment]
是不是n张卡训练但是m张卡加载模型的问题，可以看看这个https://www.cnblogs.com/jinjunweina/p/12671833.html

**Comment by Yizhou-Li-CV** [comment]
> 是不是n张卡训练但是m张卡加载模型的问题，可以看看这个https://www.cnblogs.com/jinjunweina/p/12671833.html

Thanks for your suggestion.

It is still strange that as unexpected keys are "Up4.up.1.weight", "Up4.up.1.bias", **but not** "module.Up4.up.1.weight", "module.Up4.up.1.bias", it seems net is wrapped by DataParallel (making its state_dict's keys include "module"), but not unwrapped as nn.Module (making net still require keys like "module.Up4.up.1.weight" rather than "Up4.up.1.weight" in pretrained models) **which should have already been done in**
```
def load_networks(self):
   ...
   if isinstance(net, torch.nn.DataParallel):
      net = net.module  # unwrapped as nn.Module
```

It might be because of Pytorch version in implementing "load_state_dict" function.

**Comment by Yizhou-Li-CV** [comment]
A more possible issue is that in "load_network", there are codes as follows
```
                        print('original keys', state_dict.keys()) # here the state_dict denotes pretrained autoencoder's state_dict
                        if not self.continue_train and self.isTrain:
                            # load autoencoder's decoder weights to ECNet
                            state_dict_new = dict({})
                            for key in state_dict.keys():
                                if 'Up' in key:
                                    # load weights for decoder
                                    state_dict_new[key] = state_dict[key]
                                if 'Conv.' in key:
                                    # load weights of last Conv
                                    state_dict_new[key] = state_dict[key]
                            # print('new keys', state_dict_new.keys())
                            model_dict = net.state_dict()
                            model_dict.update(state_dict_new)
                            net.load_state_dict(model_dict)
```
the _model_dict_ is updated  with _state_dict_new_, meaning the keys "Up4.xxx" (included in state_dict of pretrained autoencoder) should be included in _model_dict_. However, if the architecture of _net_ (the deraining ECNet) is modified, like "Up4" is removed, there will be no keys "Up4.xxx" in _net.state_dict()_, thus leading to mismatch between _net.state_dict()_ and _model_dict_.

**Comment by biubiubiiu** [comment]
Sorry for the late reply. The error first occurs when training with a single GPU and no modification to the code is applied. It seems that this problem has been fixed in https://github.com/Yizhou-Li-CV/ECNet/commit/7e027f8349b01a08bb6b5f55dccf2d65ba22fe26. I've just pulled the latest code and everything works fine now😀

**Comment by Yizhou-Li-CV** [comment]
It's me who should be sorry 😀. Good to hear it solved.
