### ISSUE TITLE
training

### ISSUE THREAD

**Issue by zr1048028670** [Yizhou-Li-CV/ECNet#2]
Hello,I see the training  frameworks of visualizer_training and train are different. Can these two codes be used at the same time? If I use pycharm training it, the command should be same as the readme showing?

**Comment by Yizhou-Li-CV** [comment]
Thank you for your comments!

_visualizer_training.py_ is for training curve visualization by Tensorboard, where we define the module **Visualizer**.
_train.py_ is for network training, where the module **Visualizer** defined in _visualizer_training.py_ are already included and used here.

So it is totally okay to just follow the readme to run _train.py_.
