### ISSUE TITLE
RLCN

### ISSUE THREAD

**Issue by zr1048028670** [Yizhou-Li-CV/ECNet#3]
I want to know where have used RLCN in the code？I want to receive you reply! Thank you very much!

**Comment by lonely6628** [comment]
Hello, did you run this code successfully? May I ask you some questions?

**Comment by zr1048028670** [comment]
> Reference
I haven't run it successfully!

**Comment by zr1048028670** [comment]
> Hello, did you run this code successfully? May I ask you some questions?

I cannot help you because I haven't run it successfully.

**Comment by lonely6628** [comment]
All right. It doesn't matter. Thank you very much for your reply!

**Comment by Yizhou-Li-CV** [comment]
I am sorry I just noticed your issue. Thank you very much for your question. 
RLCN is used in ECNet/models/deraining/ecnet_train_test_model.py. RLCN image is calculated here and sent to ECNet as one of the inputs of ECNet's forward function.
