### ISSUE TITLE
Hello, can I ask you a few questions?

### ISSUE THREAD

**Issue by lonely6628** [Yizhou-Li-CV/ECNet#4]
Thank you very much for sharing!  
I'm sorry to bother you, because my foundation is really not very good, and I encountered several problems when running this code. I would really appreciate it if you could give me some guidance!

Fistly, in the code of "python train.py --dataroot./data/SPA-Data_6385_patch --name &lt; autoencoder_path&gt;  --model autoencoder_train --dataset_mode rain100h --preprocess none --n_epochs 100 --lr_policy multistep  Where gradient_clipping 5", does "autoencoder_path" refer to the path of the "autoencoder_train_model.py" file?

Secondly, if I'm right about the first question, I revised "autoencoder_path" to the path of the "autoencoder_train_model.py" file.    Then I encountered this error: ModuleNotFoundError: No module named 'models. deraining. derainlcn_model'.
In the deraining folder, I do not find the file "derainlcn_model". Is it "RLCN.py"?

Wish you good health and smooth work during the epidemic! Looking forward to your reply!

**Comment by Yizhou-Li-CV** [comment]
Thank you very much for your question and sorry for the late reply.

Firstly, as written in the **Training** section of README, "trained models can be found at ./checkpoints/<autoencoder_path>". So <autoencoder_path> simply means your expected directory name to save the trained models of autoencoder.

Secondly, I wrongly set the default for "--model" param for "train.py" as "derainlcn", which actually not exists. I will correct this issue later. But this will not be a problem, you may try to set the "--model" param when executing "python train.py". Set "--model autoencoder_train" for autoencoder training, and "--model ecnet_train_test" for ECNet training, as you may see in the example command in the README.

Hope this issue can be solved. Good luck!
