### ISSUE TITLE
About the training process

### ISSUE THREAD

**Issue by mawei-north** [Yizhou-Li-CV/ECNet#5]
Hello, when I trained the rain100L dataset, the psnr value and ssim value have always been small, what is the reason why it does not match the data in the paper?

**Comment by Yizhou-Li-CV** [comment]
Thank you very much for your attention. During our experiments, there will always be different results in retraining even we fix the random seed, but it should be within an acceptable range. Is this for your case?

**Comment by 497329284** [comment]
Hello, during the testing process, I set the file path and file name according to your method. Why did I keep reporting an error message that I couldn't find the image file?
